apiVersion: v1
kind: ConfigMap
metadata:
  name: symbioai-config
data:
  cors-origins: "https://anikjain4470.github.io/symbio.ai"
---
apiVersion: v1
kind: Secret
metadata:
  name: symbioai-secrets
type: Opaque
stringData:
  mongodb-uri: "mongodb+srv://jainanik84_db_user:<YOUR_PASSWORD>@cluster0.nod8nma.mongodb.net/symbioai?retryWrites=true&w=majority&appName=Cluster0"
  secret-key: "change-me-in-production"
